version: '3.6'
services:
  wow-legion-database:
    image: ragedunicorn/mysql:${MYSQL_TAG_VERSION}-dev
    environment:
      - MYSQL_APP_USER=app
      - MYSQL_APP_PASSWORD=app
    volumes:
      - wow_legion_mysql_data:/var/lib/mysql
    expose:
        - "3306"
    ports:
      - "3306:3306"
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
    labels:
      com.ragedunicorn.mysql.environment: "dev"
      com.ragedunicorn.mysql.description: "MySQL"
  wow-legion-server:
    build: .
    image: ragedunicorn/wow-legion:${WOW_LEGION_TAG_VERSION}-dev
    environment:
      - MYSQL_APP_USER=app
      - MYSQL_APP_PASSWORD=app
      - DATABASE_HOSTNAME=wow-legion-database
    volumes:
      - wow_legion_log_data:/var/log/wow
      - ./data:/opt/legion/data
    ports:
      - "1119:1119"
      - "8081:8081"
      - "8085:8085"
      - "8086:8086"
    depends_on:
      - wow-legion-database
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
    labels:
      com.ragedunicorn.wow-legion.environment: "dev"
      com.ragedunicorn.wow-legion.description: "World of Warcraft Legion Server"
volumes:
  wow_legion_mysql_data: {}
  wow_legion_log_data: {}
